# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               GrowLove
tagline:             'Adaptive Text Repository'
description:         'A dreamer: lost in an infinitely colorful shifting landscape'
url:                 https://lionize.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark A. Chandler, II
  url:               https://twitter.com/grow_love
  email:             mark.allen.chandler@gmail.com

# Custom vars
version:             1.0.0
